trigger:
  branches:
    include:
      - main

pool:
  name: 'New Self-Hosted Agent'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'acr-connection'
      repository: 'dccloudsaquibacr/my-app'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        latest
