trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'New Self-Hosted Agent'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'acr-connection'  # Use the correct service connection name
      repository: 'dccloudsaquibacr/my-app'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'  # Ensure your Dockerfile exists
      tags: |
        latest
